# Based on this one: https://github.com/springboot-testcontainer/springboot-testcontainer-selenium/blob/99e2440edc89ac15b4abbae568e7912572b8cce3/.github/workflows/release.yml
name: Pack & Publish

on: [push, pull_request]
    

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: setup-gpg
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      run: echo ${GPG_PRIVATE_KEY} | base64 --decode | gpg --batch --import

    - name: setup-maven-settings
      uses: s4u/maven-settings-action@v1
      with:
        servers: '[{"id": "ossrh", "username": "${OSSRH_USERNAME}", "password": "${OSSRH_PASSWORD}"}, {"id": "github", "username": "x-access-token", "password": "${GITHUB_TOKEN}"}]'
        properties: '[{"gpg.executable": "gpg"}, {"gpg.passphrase": "${GPG_PASSPHRASE}"}]'
        sonatypeSnapshots: true

    - name: Build with Maven
      run: mvn -B clean compile package --file pom.xml
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: artifacts
        path: ./target/
    - name: Publish package
      env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      run: mvn deploy
      if: github.ref == 'refs/heads/master' 
